os: windows
language: shell
service:
  - docker

# if: branch = master
if: tag IS present

script:
# - powershell set-executionpolicy unrestricted
  - docker build -t "pixpan/steamcmd-wincore" .
  - docker tag pixpan/steamcmd-wincore "pixpan/steamcmd-wincore:$TRAVIS_BUILD_NUMBER"
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker push "pixpan/steamcmd-wincore"
